In [1]:
!ls /data

ira.csv  PortfolioDownload.csv

In [2]:
import pandas as pd

# read csv file
cars = pd.read_csv("/data/ira.csv")

# display DataFrame
print(cars)

   Symbol  Last Price $  Change $  Change %     Qty #  Price Paid $  \
0     PSA      307.9400      5.22      1.72    40.000      199.9538
1    SHOP     1538.0300     73.28      5.00     1.000     1468.0400
2    HNDL       25.8000      0.05      0.19   771.000       25.3592
3    LEVI       28.2700      0.81      2.95    36.000       27.5985
4    QFIN       34.2800     -1.46     -4.09    30.000       33.8500
5    CRWD      264.9800     12.39      4.91     2.000      258.6900
6      ZM      401.1200     12.23      3.14     1.000      392.5800
7    NFLX      541.6400      7.66      1.43     1.000      533.5000
8    AAPL      142.0200      2.06      1.47     4.000      140.0900
9    TEAM      268.4300      5.71      2.17     1.000      262.9900
10   FVRR      241.8200      0.82      0.34     2.000      241.7700
11  FNMIX       14.7100      0.00      0.00   935.125       15.8472
12  SCNTQ        0.0098      0.00      0.00     4.000        0.0000
13   MDIV       17.0400     -0.01     -0.06    61.000       16.3000
14   NVDA      827.9400      8.46      1.03     1.000      829.8600
15    SPY      432.9300     -0.79     -0.18     3.000      433.7500
16   BJUL       31.5548     -0.05     -0.14    30.000       31.6700
17   ABNB      148.3700     -1.86     -1.24     3.000      150.0800
18    DIS      173.6900     -3.42     -1.93     2.000      176.7800
19    GPP       12.5000     -0.04     -0.32   200.000       12.7287
20    MPW       20.3800     -0.22     -1.07    50.000       20.4194
21    HYG       88.0100     -0.05     -0.06   290.000       86.9628
22   MARA       29.7200     -0.57     -1.88    33.000       30.5395
23   COIN      235.4100     -5.31     -2.21     5.000      229.9009
24  DODGX      238.0400     -3.89     -1.61     8.642      232.1452
25    CFG       44.7000     -1.35     -2.93   200.000       37.2194
26  VGHCX      235.9000     -1.62     -0.68   208.296      168.5841
27    DBC       18.9700     -0.53     -2.72   875.000       17.7130
28  WMCVX       10.9300     -0.16     -1.44  3848.566        3.8766

    Day's Gain $  Total Gain $  Total Gain %     Value $
0       208.8000     4314.4500       53.9094  12317.6000
1        69.9900       69.9900        4.7676   1538.0300
2        38.5500      339.8900        1.7384  19891.8000
3        29.1600       24.1740        2.4331   1017.7200
4        12.9000       12.9000        1.2703   1028.4000
5        12.5800       12.5800        2.4315    529.9600
6         8.5400        8.5400        2.1754    401.1200
7         8.1400        8.1400        1.5258    541.6400
8         7.7200        7.7200        1.3777    568.0800
9         5.4400        5.4400        2.0685    268.4300
10        0.1000        0.1000        0.0207    483.6400
11        0.0000    -1073.4410       -7.2387  13755.6887
12        0.0000        0.0392        0.0000      0.0392
13       -0.6100       45.1400        4.5399   1039.4400
14       -1.9200       -1.9200       -0.2314    827.9400
15       -2.4600       -2.4600       -0.1890   1298.7900
16       -3.4560       -3.4560       -0.3638    946.6440
17       -5.1300       -5.1300       -1.1394    445.1100
18       -6.1800       -6.1800       -1.7479    347.3800
19       -8.0000      -45.7500       -1.7971   2500.0000
20      -11.0000       -1.9700       -0.1930   1019.0000
21      -14.5000      303.6767        1.2041  25522.9000
22      -18.8100      -27.0435       -2.6834    980.7600
23      -26.5500       27.5455        2.3963   1177.0500
24      -33.6174       40.9432        2.0307   2057.1417
25     -270.0000     1491.1281       20.0182   8940.0000
26     -337.4395    14021.6410       39.9302  49137.0264
27     -463.7500     1059.8408        6.8206  16598.7500
28     -615.7706    27140.5907      181.8558  42064.8264

In [3]:
cars

,Symbol,Last Price $,Change $,Change %,Qty #,Price Paid $,Day's Gain $,Total Gain $,Total Gain %,Value $
0,PSA,307.9400,5.22,1.72,40.000,199.9538,208.8000,4314.4500,53.9094,12317.6000
1,SHOP,1538.0300,73.28,5.00,1.000,1468.0400,69.9900,69.9900,4.7676,1538.0300
2,HNDL,25.8000,0.05,0.19,771.000,25.3592,38.5500,339.8900,1.7384,19891.8000
3,LEVI,28.2700,0.81,2.95,36.000,27.5985,29.1600,24.1740,2.4331,1017.7200
4,QFIN,34.2800,-1.46,-4.09,30.000,33.8500,12.9000,12.9000,1.2703,1028.4000
5,CRWD,264.9800,12.39,4.91,2.000,258.6900,12.5800,12.5800,2.4315,529.9600
6,ZM,401.1200,12.23,3.14,1.000,392.5800,8.5400,8.5400,2.1754,401.1200
7,NFLX,541.6400,7.66,1.43,1.000,533.5000,8.1400,8.1400,1.5258,541.6400
8,AAPL,142.0200,2.06,1.47,4.000,140.0900,7.7200,7.7200,1.3777,568.0800
9,TEAM,268.4300,5.71,2.17,1.000,262.9900,5.4400,5.4400,2.0685,268.4300
10,FVRR,241.8200,0.82,0.34,2.000,241.7700,0.1000,0.1000,0.0207,483.6400
11,FNMIX,14.7100,0.00,0.00,935.125,15.8472,0.0000,-1073.4410,-7.2387,13755.6887
12,SCNTQ,0.0098,0.00,0.00,4.000,0.0000,0.0000,0.0392,0.0000,0.0392
13,MDIV,17.0400,-0.01,-0.06,61.000,16.3000,-0.6100,45.1400,4.5399,1039.4400
14,NVDA,827.9400,8.46,1.03,1.000,829.8600,-1.9200,-1.9200,-0.2314,827.9400
15,SPY,432.9300,-0.79,-0.18,3.000,433.7500,-2.4600,-2.4600,-0.1890,1298.7900
16,BJUL,31.5548,-0.05,-0.14,30.000,31.6700,-3.4560,-3.4560,-0.3638,946.6440
17,ABNB,148.3700,-1.86,-1.24,3.000,150.0800,-5.1300,-5.1300,-1.1394,445.1100
18,DIS,173.6900,-3.42,-1.93,2.000,176.7800,-6.1800,-6.1800,-1.7479,347.3800
19,GPP,12.5000,-0.04,-0.32,200.000,12.7287,-8.0000,-45.7500,-1.7971,2500.0000
20,MPW,20.3800,-0.22,-1.07,50.000,20.4194,-11.0000,-1.9700,-0.1930,1019.0000
21,HYG,88.0100,-0.05,-0.06,290.000,86.9628,-14.5000,303.6767,1.2041,25522.9000
22,MARA,29.7200,-0.57,-1.88,33.000,30.5395,-18.8100,-27.0435,-2.6834,980.7600
23,COIN,235.4100,-5.31,-2.21,5.000,229.9009,-26.5500,27.5455,2.3963,1177.0500
24,DODGX,238.0400,-3.89,-1.61,8.642,232.1452,-33.6174,40.9432,2.0307,2057.1417
25,CFG,44.7000,-1.35,-2.93,200.000,37.2194,-270.0000,1491.1281,20.0182,8940.0000
26,VGHCX,235.9000,-1.62,-0.68,208.296,168.5841,-337.4395,14021.6410,39.9302,49137.0264
27,DBC,18.9700,-0.53,-2.72,875.000,17.7130,-463.7500,1059.8408,6.8206,16598.7500
28,WMCVX,10.9300,-0.16,-1.44,3848.566,3.8766,-615.7706,27140.5907,181.8558,42064.8264

In [8]:
# read csv file
motley = pd.read_csv("/data/motley.csv")

# display DataFrame
motley

  Symbol  Price - 7-5-2021  NumShares  CostBasis     PE
0   ABNB            150.23          3    $450.69    NaN
1   AAPL            139.96          4    $559.84   30.8
2   TEAM            262.72          1    $262.72    NaN
3   CRWD            252.59          2    $505.18    NaN
4   FVRR            241.00          2    $482.00    NaN
5   NFLX            533.98          1    $533.98   66.0
6   NVDA            819.48          1    $819.48   95.0
7    DIS            177.11          2    $354.22    NaN
8   SHOP           1464.70          1  $1,464.70  114.0
9     ZM            388.89          1    $388.89  135.0

In [19]:
cdf  = pd.DataFrame()
for sym in motley['Symbol']:
    print(sym)
    mdf = cars.loc[cars['Symbol'] == sym]
    print(mdf)
    cdf = cdf.append(mdf)

ABNB
   Symbol  Last Price $  Change $  Change %  Qty #  Price Paid $  \
17   ABNB        148.37     -1.86     -1.24    3.0        150.08

    Day's Gain $  Total Gain $  Total Gain %  Value $
17         -5.13         -5.13       -1.1394   445.11
AAPL
  Symbol  Last Price $  Change $  Change %  Qty #  Price Paid $  Day's Gain $  \
8   AAPL        142.02      2.06      1.47    4.0        140.09          7.72

   Total Gain $  Total Gain %  Value $
8          7.72        1.3777   568.08
TEAM
  Symbol  Last Price $  Change $  Change %  Qty #  Price Paid $  Day's Gain $  \
9   TEAM        268.43      5.71      2.17    1.0        262.99          5.44

   Total Gain $  Total Gain %  Value $
9          5.44        2.0685   268.43
CRWD
  Symbol  Last Price $  Change $  Change %  Qty #  Price Paid $  Day's Gain $  \
5   CRWD        264.98     12.39      4.91    2.0        258.69         12.58

   Total Gain $  Total Gain %  Value $
5         12.58        2.4315   529.96
FVRR
   Symbol  Last Price $  Change $  Change %  Qty #  Price Paid $  \
10   FVRR        241.82      0.82      0.34    2.0        241.77

    Day's Gain $  Total Gain $  Total Gain %  Value $
10           0.1           0.1        0.0207   483.64
NFLX
  Symbol  Last Price $  Change $  Change %  Qty #  Price Paid $  Day's Gain $  \
7   NFLX        541.64      7.66      1.43    1.0         533.5          8.14

   Total Gain $  Total Gain %  Value $
7          8.14        1.5258   541.64
NVDA
   Symbol  Last Price $  Change $  Change %  Qty #  Price Paid $  \
14   NVDA        827.94      8.46      1.03    1.0        829.86

    Day's Gain $  Total Gain $  Total Gain %  Value $
14         -1.92         -1.92       -0.2314   827.94
DIS
   Symbol  Last Price $  Change $  Change %  Qty #  Price Paid $  \
18    DIS        173.69     -3.42     -1.93    2.0        176.78

    Day's Gain $  Total Gain $  Total Gain %  Value $
18         -6.18         -6.18       -1.7479   347.38
SHOP
  Symbol  Last Price $  Change $  Change %  Qty #  Price Paid $  Day's Gain $  \
1   SHOP       1538.03     73.28       5.0    1.0       1468.04         69.99

   Total Gain $  Total Gain %  Value $
1         69.99        4.7676  1538.03
ZM
  Symbol  Last Price $  Change $  Change %  Qty #  Price Paid $  Day's Gain $  \
6     ZM        401.12     12.23      3.14    1.0        392.58          8.54

   Total Gain $  Total Gain %  Value $
6          8.54        2.1754   401.12

In [20]:
cdf

,Symbol,Last Price $,Change $,Change %,Qty #,Price Paid $,Day's Gain $,Total Gain $,Total Gain %,Value $
17,ABNB,148.37,-1.86,-1.24,3.0,150.08,-5.13,-5.13,-1.1394,445.11
8,AAPL,142.02,2.06,1.47,4.0,140.09,7.72,7.72,1.3777,568.08
9,TEAM,268.43,5.71,2.17,1.0,262.99,5.44,5.44,2.0685,268.43
5,CRWD,264.98,12.39,4.91,2.0,258.69,12.58,12.58,2.4315,529.96
10,FVRR,241.82,0.82,0.34,2.0,241.77,0.10,0.10,0.0207,483.64
7,NFLX,541.64,7.66,1.43,1.0,533.50,8.14,8.14,1.5258,541.64
14,NVDA,827.94,8.46,1.03,1.0,829.86,-1.92,-1.92,-0.2314,827.94
18,DIS,173.69,-3.42,-1.93,2.0,176.78,-6.18,-6.18,-1.7479,347.38
1,SHOP,1538.03,73.28,5.00,1.0,1468.04,69.99,69.99,4.7676,1538.03
6,ZM,401.12,12.23,3.14,1.0,392.58,8.54,8.54,2.1754,401.12

In [22]:
tdf = cdf.sum(axis=0)

In [23]:
tdf

Symbol          ABNBAAPLTEAMCRWDFVRRNFLXNVDADISSHOPZM
Last Price $                                  4548.04
Change $                                       117.33
Change %                                        16.32
Qty #                                            18.0
Price Paid $                                  4454.38
Day's Gain $                                    99.28
Total Gain $                                    99.28
Total Gain %                                  11.2485
Value $                                       5951.33
dtype: object

In [24]:
total_gain = tdf['Total Gain $']

In [25]:
total_gain

99.28

In [26]:
value = tdf['Value $']

In [27]:
value

5951.33

In [29]:
pct = total_gain/(value - total_gain)*100

In [30]:
pct

1.6964995172631812