In [1]:
!ls /data

ira.csv        motley.csv	      taxable.csv	tonyindex.csv
kiplinger.csv  PortfolioDownload.csv  tonydividend.csv	tonyira.csv

In [2]:
import pandas as pd

# read csv file
cars = pd.read_csv("/data/taxable.csv")

# display DataFrame
#print(cars)

In [3]:
#cars

In [4]:
# read csv file
motley = pd.read_csv("/data/tonydividend.csv")

# display DataFrame
motley

,Symbol,Last Price $,Change $,Change %,Qty #,Price Paid $,Day's Gain $,Total Gain $,Total Gain %,Value $
0,XEL,67.07,0.25,0.37,225.0,21.8631,56.25,10153.7700,205.6676,15090.75
1,KMB,134.64,0.29,0.22,56.0,61.9610,16.44,4050.8600,116.1044,7539.84
2,PEP,149.13,0.22,0.15,53.0,66.2541,11.12,4382.4200,124.4486,7903.89
3,PFE,39.29,-0.44,-1.11,8.0,39.4900,-1.60,-1.6000,-0.5065,314.32
4,MCD,232.75,-0.88,-0.38,2.0,233.6600,-1.82,-1.8200,-0.3895,465.50
5,CPB,45.54,-0.12,-0.26,92.0,35.3999,-10.76,922.8900,28.2507,4189.68
6,ADM,59.45,-1.18,-1.95,20.0,60.2800,-16.60,-16.6000,-1.3769,1189.00
7,WMT,139.94,-0.17,-0.12,187.0,58.7264,-31.79,15149.4507,137.4807,26168.78
8,GSK,40.06,-0.35,-0.87,100.0,38.2987,-35.00,161.1350,4.1909,4006.00
9,WBA,47.70,-0.47,-0.98,180.0,53.6126,-84.60,-1084.2720,-11.2124,8586.00
10,CVS,81.18,-1.25,-1.52,220.0,64.1690,-275.00,3712.4290,26.2415,17859.60

In [5]:
cdf  = pd.DataFrame()
for sym in motley['Symbol']:
    print(sym)
    mdf = cars.loc[cars['Symbol'] == sym]
    print(mdf)
    cdf = cdf.append(mdf)

XEL
  Symbol  Last Price $  Change $  Change %  Qty #  Price Paid $  Day's Gain $  \
1    XEL         67.07      0.25      0.37  225.0       21.8631         56.25

   Total Gain $  Total Gain %   Value $  Dividend Yield %
1      10153.77      205.6676  15090.75            2.7387
KMB
  Symbol  Last Price $  Change $  Change %  Qty #  Price Paid $  Day's Gain $  \
3    KMB        134.64      0.29      0.22   56.0        61.961         16.44

   Total Gain $  Total Gain %  Value $  Dividend Yield %
3       4050.86      116.1044  7539.84            3.3941
PEP
  Symbol  Last Price $  Change $  Change %  Qty #  Price Paid $  Day's Gain $  \
5    PEP        149.13      0.22      0.15   53.0       66.2541         11.12

   Total Gain $  Total Gain %  Value $  Dividend Yield %
5       4382.42      124.4486  7903.89            2.8877
PFE
   Symbol  Last Price $  Change $  Change %  Qty #  Price Paid $  \
15    PFE         39.29     -0.44     -1.11    8.0         39.49

    Day's Gain $  Total Gain $  Total Gain %  Value $  Dividend Yield %
15          -1.6          -1.6       -0.5065   314.32            3.9265
MCD
   Symbol  Last Price $  Change $  Change %  Qty #  Price Paid $  \
16    MCD        232.75     -0.88     -0.38    2.0        233.66

    Day's Gain $  Total Gain $  Total Gain %  Value $  Dividend Yield %
16         -1.82         -1.82       -0.3895    465.5            2.2086
CPB
   Symbol  Last Price $  Change $  Change %  Qty #  Price Paid $  \
25    CPB         45.54     -0.12     -0.26   92.0       35.3999

    Day's Gain $  Total Gain $  Total Gain %  Value $  Dividend Yield %
25        -10.76        922.89       28.2507  4189.68            3.2413
ADM
   Symbol  Last Price $  Change $  Change %  Qty #  Price Paid $  \
30    ADM         59.45     -1.18     -1.95   20.0         60.28

    Day's Gain $  Total Gain $  Total Gain %  Value $  Dividend Yield %
30         -16.6         -16.6       -1.3769   1189.0             2.441
WMT
   Symbol  Last Price $  Change $  Change %  Qty #  Price Paid $  \
35    WMT        139.94     -0.17     -0.12  187.0       58.7264

    Day's Gain $  Total Gain $  Total Gain %   Value $  Dividend Yield %
35        -31.79    15149.4507      137.4807  26168.78            1.5702
GSK
   Symbol  Last Price $  Change $  Change %  Qty #  Price Paid $  \
36    GSK         40.06     -0.35     -0.87  100.0       38.2987

    Day's Gain $  Total Gain $  Total Gain %  Value $  Dividend Yield %
36         -35.0       161.135        4.1909   4006.0            5.3781
WBA
   Symbol  Last Price $  Change $  Change %  Qty #  Price Paid $  \
41    WBA          47.7     -0.47     -0.98  180.0       53.6126

    Day's Gain $  Total Gain $  Total Gain %  Value $  Dividend Yield %
41         -84.6     -1084.272      -11.2124   8586.0            3.8821
CVS
   Symbol  Last Price $  Change $  Change %  Qty #  Price Paid $  \
47    CVS         81.18     -1.25     -1.52  220.0        64.169

    Day's Gain $  Total Gain $  Total Gain %  Value $  Dividend Yield %
47        -275.0      3712.429       26.2415  17859.6            2.4263

In [6]:
cdf

,Symbol,Last Price $,Change $,Change %,Qty #,Price Paid $,Day's Gain $,Total Gain $,Total Gain %,Value $,Dividend Yield %
1,XEL,67.07,0.25,0.37,225.0,21.8631,56.25,10153.7700,205.6676,15090.75,2.7387
3,KMB,134.64,0.29,0.22,56.0,61.9610,16.44,4050.8600,116.1044,7539.84,3.3941
5,PEP,149.13,0.22,0.15,53.0,66.2541,11.12,4382.4200,124.4486,7903.89,2.8877
15,PFE,39.29,-0.44,-1.11,8.0,39.4900,-1.60,-1.6000,-0.5065,314.32,3.9265
16,MCD,232.75,-0.88,-0.38,2.0,233.6600,-1.82,-1.8200,-0.3895,465.50,2.2086
25,CPB,45.54,-0.12,-0.26,92.0,35.3999,-10.76,922.8900,28.2507,4189.68,3.2413
30,ADM,59.45,-1.18,-1.95,20.0,60.2800,-16.60,-16.6000,-1.3769,1189.00,2.4410
35,WMT,139.94,-0.17,-0.12,187.0,58.7264,-31.79,15149.4507,137.4807,26168.78,1.5702
36,GSK,40.06,-0.35,-0.87,100.0,38.2987,-35.00,161.1350,4.1909,4006.00,5.3781
41,WBA,47.70,-0.47,-0.98,180.0,53.6126,-84.60,-1084.2720,-11.2124,8586.00,3.8821
47,CVS,81.18,-1.25,-1.52,220.0,64.1690,-275.00,3712.4290,26.2415,17859.60,2.4263

In [7]:
tdf = cdf.sum(axis=0)

In [8]:
tdf

Symbol              XELKMBPEPPFEMCDCPBADMWMTGSKWBACVS
Last Price $                                  1036.75
Change $                                         -4.1
Change %                                        -6.45
Qty #                                          1143.0
Price Paid $                                 733.7148
Day's Gain $                                  -373.36
Total Gain $                               37428.6627
Total Gain %                                 628.8991
Value $                                      93313.36
Dividend Yield %                              34.0946
dtype: object

In [9]:
total_gain = tdf['Total Gain $']

In [10]:
total_gain

37428.6627

In [11]:
value = tdf['Value $']

In [12]:
value

93313.36000000002

In [13]:
pct = total_gain/(value - total_gain)*100

In [14]:
pct

66.97479723129858

In [15]:
cdf['income'] = cdf['Dividend Yield %']/100 * cdf['Value $']

In [16]:
cdf

,Symbol,Last Price $,Change $,Change %,Qty #,Price Paid $,Day's Gain $,Total Gain $,Total Gain %,Value $,Dividend Yield %,income
1,XEL,67.07,0.25,0.37,225.0,21.8631,56.25,10153.7700,205.6676,15090.75,2.7387,413.290370
3,KMB,134.64,0.29,0.22,56.0,61.9610,16.44,4050.8600,116.1044,7539.84,3.3941,255.909709
5,PEP,149.13,0.22,0.15,53.0,66.2541,11.12,4382.4200,124.4486,7903.89,2.8877,228.240632
15,PFE,39.29,-0.44,-1.11,8.0,39.4900,-1.60,-1.6000,-0.5065,314.32,3.9265,12.341775
16,MCD,232.75,-0.88,-0.38,2.0,233.6600,-1.82,-1.8200,-0.3895,465.50,2.2086,10.281033
25,CPB,45.54,-0.12,-0.26,92.0,35.3999,-10.76,922.8900,28.2507,4189.68,3.2413,135.800098
30,ADM,59.45,-1.18,-1.95,20.0,60.2800,-16.60,-16.6000,-1.3769,1189.00,2.4410,29.023490
35,WMT,139.94,-0.17,-0.12,187.0,58.7264,-31.79,15149.4507,137.4807,26168.78,1.5702,410.902184
36,GSK,40.06,-0.35,-0.87,100.0,38.2987,-35.00,161.1350,4.1909,4006.00,5.3781,215.446686
41,WBA,47.70,-0.47,-0.98,180.0,53.6126,-84.60,-1084.2720,-11.2124,8586.00,3.8821,333.317106
47,CVS,81.18,-1.25,-1.52,220.0,64.1690,-275.00,3712.4290,26.2415,17859.60,2.4263,433.327475

In [17]:
cdf.sum(axis=0)['income']

2477.88055722